### ISSUE TITLE
[유저 피드백] 안드로이드 환경에서 간헐적으로 결과가 출력 되지 않습니다. 

### ISSUE THREAD

**Issue by hyeon9782** [f-lab-edu/Find_Character_GPT#135]
![image](https://github.com/f-lab-edu/Find_Character_GPT/assets/62998723/847000dd-aeb0-4e24-b2b4-55c93025f68d)

다음과 같은 에러가 발생하면서 결과가 출력 되지 않습니다.

그리고 에러 발생시 Loading 화면에 계속 표시되기 때문에 에러가 발생하면 다시 시도하는 로직이 있는 화면을 보여줬으면 좋겠습니다.

**Comment by nara04040** [comment]
현재 edge function + stream을 도입하여 에러를 고쳐볼려고합니다. 
소중한 피드백 감사합니다.🙇🏻

**Comment by nara04040** [comment]
에러수정 완료✅
